version: '3.8'

# Docker Compose for TEST environment
# Port 8001 for parallel testing

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ventanas-test-app
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=true
    env_file:
      - .env
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 90s
